-- MySQL Script generated by MySQL Workbench
-- Sun Jun 18 22:23:39 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ciberimpacto
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ciberimpacto` ;

-- -----------------------------------------------------
-- Schema ciberimpacto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ciberimpacto` DEFAULT CHARACTER SET utf8 ;
USE `ciberimpacto` ;

-- -----------------------------------------------------
-- Table `ciberimpacto`.`tb_marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ciberimpacto`.`tb_marca` (
  `codMarca` 	  INT         NOT NULL,
  `nombreMarca` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codMarca`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ciberimpacto`.`tb_CPU`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ciberimpacto`.`tb_CPU` (
  `codCPU` 		  INT         NOT NULL,
  `codMarca` 	  INT         NOT NULL,
  `nombreCPU` 	VARCHAR(45) NOT NULL,
  `modeloCPU` 	VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codCPU`),
  INDEX `fk_tbCPU_tbMarca:codMarca_idx` (`codMarca` ASC) VISIBLE,
  CONSTRAINT `fk_tbCPU_tbMarca:codMarca`
    FOREIGN KEY (`codMarca`)
    REFERENCES `ciberimpacto`.`tb_marca` (`codMarca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ciberimpacto`.`tb_GPU`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ciberimpacto`.`tb_GPU` (
  `codGPU` 		  INT         NOT NULL,
  `codMarca` 	  INT         NOT NULL,
  `nombre` 		  VARCHAR(45) NOT NULL,
  `capacidad` 	VARCHAR(5)  NOT NULL,
  PRIMARY KEY (`codGPU`),
  INDEX `fk_tbGPU_tbMarca:codMarca_idx` (`codMarca` ASC) VISIBLE,
  CONSTRAINT `fk_tbGPU_tbMarca:codMarca`
    FOREIGN KEY (`codMarca`)
    REFERENCES `ciberimpacto`.`tb_marca` (`codMarca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ciberimpacto`.`tb_tipoDiscoDuro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ciberimpacto`.`tb_tipoDiscoDuro` (
  `codTipoDiscoDuro` 	INT         NOT NULL,
  `nombreTipo` 			  VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codTipoDiscoDuro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ciberimpacto`.`tb_discoDuro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ciberimpacto`.`tb_discoDuro` (
  `codDiscoDuro` 		  INT         NOT NULL,
  `codMarca` 			    INT         NOT NULL,
  `capacidad` 		  	VARCHAR(5)  NOT NULL,
  `codTipoDiscoDuro` 	INT         NOT NULL,
  PRIMARY KEY (`codDiscoDuro`),
  INDEX `fk_tbDiscoDuro_tbTipoDIscoDuro:codTipoDiscoDuro_idx` (`codTipoDiscoDuro` ASC) VISIBLE,
  INDEX `fk_tbDiscoDuro_tbMarca_idx` (`codMarca` ASC) VISIBLE,
  CONSTRAINT `fk_tbDiscoDuro_tbTipoDIscoDuro:codTipoDiscoDuro`
    FOREIGN KEY (`codTipoDiscoDuro`)
    REFERENCES `ciberimpacto`.`tb_tipoDiscoDuro` (`codTipoDiscoDuro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbDiscoDuro_tbMarca`
    FOREIGN KEY (`codMarca`)
    REFERENCES `ciberimpacto`.`tb_marca` (`codMarca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ciberimpacto`.`tb_categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ciberimpacto`.`tb_categoria` (
  `codCategoria` 	  INT         NOT NULL,
  `nombreCategoria` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codCategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ciberimpacto`.`tb_SistemaOperativo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ciberimpacto`.`tb_SistemaOperativo` (
  `codSistemaOperativo` INT         NOT NULL,
  `nombre` 			      	VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codSistemaOperativo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ciberimpacto`.`tb_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ciberimpacto`.`tb_producto` (
  `codProducto` 		    VARCHAR(5)    NOT NULL,
  `nombreProducto` 		  VARCHAR(45)   NOT NULL,
  `descripcionProducto` VARCHAR(150)  NOT NULL,
  `codCategoria` 		    INT           NOT NULL,
  `codMarca` 			      INT           NOT NULL,
  `modeloProducto`	 	  VARCHAR(45)   NOT NULL,
  `descripcionPantalla` VARCHAR(150)  NOT NULL,
  `codCPU` 				      INT           NOT NULL,
  `codGPU` 				      INT           NOT NULL,
  `codDiscoDuro` 		    INT           NOT NULL,
  `codSistemaOperativo` INT           NOT NULL,
  `precioVenta` 		    DECIMAL(7,2)  NOT NULL,
  PRIMARY KEY (`codProducto`),
  INDEX `fk_tbProducto_tbMarca:codMarca_idx` (`codMarca` ASC) VISIBLE,
  INDEX `fk_tbProducto_tbGPU_idx` (`codCPU` ASC) VISIBLE,
  INDEX `fk_tbProducto_tbGPU_idx1` (`codGPU` ASC) VISIBLE,
  INDEX `fk_tbProducto_tbDiscoDuro:codDiscoDuro_idx` (`codDiscoDuro` ASC) VISIBLE,
  INDEX `fk_tbProducto_tbTipoProducto:codTipoProducto_idx` (`codCategoria` ASC) VISIBLE,
  INDEX `fk_tbProducto_tbSistemaOperativo:codSistemaOperativo_idx` (`codSistemaOperativo` ASC) VISIBLE,
  CONSTRAINT `fk_tbProducto_tbMarca:codMarca`
    FOREIGN KEY (`codMarca`)
    REFERENCES `ciberimpacto`.`tb_marca` (`codMarca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbProducto_tbCPU:codCPU`
    FOREIGN KEY (`codCPU`)
    REFERENCES `ciberimpacto`.`tb_CPU` (`codCPU`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbProducto_tbGPU:codGPU`
    FOREIGN KEY (`codGPU`)
    REFERENCES `ciberimpacto`.`tb_GPU` (`codGPU`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbProducto_tbDiscoDuro:codDiscoDuro`
    FOREIGN KEY (`codDiscoDuro`)
    REFERENCES `ciberimpacto`.`tb_discoDuro` (`codDiscoDuro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbProducto_tbCategoria:codCategoria`
    FOREIGN KEY (`codCategoria`)
    REFERENCES `ciberimpacto`.`tb_categoria` (`codCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbProducto_tbSistemaOperativo:codSistemaOperativo`
    FOREIGN KEY (`codSistemaOperativo`)
    REFERENCES `ciberimpacto`.`tb_SistemaOperativo` (`codSistemaOperativo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ciberimpacto`.`tb_TipoUsuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ciberimpacto`.`tb_TipoUsuario` (
  `codTipoUsuario` 	INT         NOT NULL,
  `nombreTipo` 		  VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codTipoUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ciberimpacto`.`tb_pais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ciberimpacto`.`tb_pais` (
  `codPais` VARCHAR(4)  NOT NULL,
  `nombre` 	VARCHAR(15) NOT NULL,
  PRIMARY KEY (`codPais`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ciberimpacto`.`tb_ciudad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ciberimpacto`.`tb_ciudad` (
  `codCiudad` 		VARCHAR(5)   NOT NULL,
  `nombreCiudad` 	VARCHAR(25) NOT NULL,
  PRIMARY KEY (`codCiudad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ciberimpacto`.`tb_TipoDocumento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ciberimpacto`.`tb_TipoDocumento` (
  `codTipoDocumento` 	INT         NOT NULL,
  `nombreTipo` 			  VARCHAR(25) NOT NULL,
  PRIMARY KEY (`codTipoDocumento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ciberimpacto`.`tb_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ciberimpacto`.`tb_usuarios` (
  `codUsuario` 			  VARCHAR(5)    NOT NULL,
  `codTipoUsuario` 		VARCHAR(5)    NOT NULL,
  `email`				      VARCHAR(100)  NOT NULL,
  `contraseña` 			  VARCHAR(16)   NOT NULL,
  `nombreCompleto` 		VARCHAR(45)   NOT NULL,
  `apellidoCompleto` 	VARCHAR(45)   NOT NULL,
  `codTipoDocumento` 	INT           NULL,
  `numeroDocumento` 	VARCHAR(45)   NULL,
  `numeroTelefonico` 	VARCHAR(45)   NULL,
  `codPais` 			    VARCHAR(45)   NULL,
  `codCiudad` 			  VARCHAR(45)   NULL,
  `numeroRUC` 			  VARCHAR(45)   NULL,
  `direccion` 			  VARCHAR(45)   NULL,
  PRIMARY KEY (`codUsuario`),
  INDEX `fk_tbUsuarios_tbTipoUsuario:codTipoUsuario_idx` (`codTipoUsuario` ASC) VISIBLE,
  INDEX `fk_tbUsuarios_tbCiudad:codCiudad_idx` (`codCiudad` ASC) VISIBLE,
  INDEX `fk_tbUsuarios_tbPais:codPais_idx` (`codPais` ASC) VISIBLE,
  INDEX `fk_tbUsuarios_tbTipoDocumento:codDocumento_idx` (`codTipoDocumento` ASC) VISIBLE,
  CONSTRAINT `fk_tbUsuarios_tbTipoUsuario:codTipoUsuario`
    FOREIGN KEY (`codTipoUsuario`)
    REFERENCES `ciberimpacto`.`tb_TipoUsuario` (`codTipoUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbUsuarios_tbCiudad:codCiudad`
    FOREIGN KEY (`codCiudad`)
    REFERENCES `ciberimpacto`.`tb_ciudad` (`codCiudad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbUsuarios_tbPais:codPais`
    FOREIGN KEY (`codPais`)
    REFERENCES `ciberimpacto`.`tb_pais` (`codPais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbUsuarios_tbTipoDocumento:codDocumento`
    FOREIGN KEY (`codTipoDocumento`)
    REFERENCES `ciberimpacto`.`tb_TipoDocumento` (`codTipoDocumento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ciberimpacto`.`tb_Factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ciberimpacto`.`tb_Factura` (
  `codFactura` 		VARCHAR(5)    NOT NULL,
  `codUsuario` 		VARCHAR(5)    NOT NULL,
  `fechaPedido` 	DATETIME      NOT NULL,
  `total` 			  DECIMAL(7,2)  NOT NULL,
  `PrecioEnvio` 	DECIMAL(4,2)  NOT NULL,
  PRIMARY KEY (`codFactura`),
  INDEX `fk_tbFactura_tbUsuario:codUsuario_idx` (`codUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_tbFactura_tbUsuario:codUsuario`
    FOREIGN KEY (`codUsuario`)
    REFERENCES `ciberimpacto`.`tb_usuarios` (`codTipoUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ciberimpacto`.`tbCarrito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ciberimpacto`.`tbCarrito` (
  `codCarrito` 	INT           NOT NULL AUTO_INCREMENT,
  `codUsuario` 	VARCHAR(5)    NOT NULL,
  `codProducto` VARCHAR(5)    NOT NULL,
  `cantidad` 	  INT           NOT NULL,
  `SubTotal` 	  DECIMAL(7,2)  NOT NULL,
  PRIMARY KEY (`codCarrito`, `codUsuario`),
  INDEX `fk_tbCarrito_tbProducto:codProducto_idx` (`codProducto` ASC) VISIBLE,
  INDEX `fk_tbCarrito_tbUsuario:codUsuario_idx` (`codUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_tbCarrito_tbProducto:codProducto`
    FOREIGN KEY (`codProducto`)
    REFERENCES `ciberimpacto`.`tb_producto` (`codProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbCarrito_tbUsuario:codUsuario`
    FOREIGN KEY (`codUsuario`)
    REFERENCES `ciberimpacto`.`tb_usuarios` (`codUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ciberimpacto`.`imagenPrueba`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ciberimpacto`.`imagenPrueba` (
  `codImagen` 	INT         NOT NULL,
  `nombre` 		  VARCHAR(50) NULL,
  `imagen` 		  LONGBLOB    NULL,
  PRIMARY KEY (`codImagen`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ciberimpacto`.`tb_DetalleFactura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ciberimpacto`.`tb_DetalleFactura` (
  `codFactura` 			    VARCHAR(5)    NOT NULL,
  `codDetalleFactura` 	INT           NOT NULL,
  `codProducto` 		    VARCHAR(5)    NOT NULL,
  `cantidad` 			      INT           NOT NULL,
  `SubTotal` 			      DECIMAL(7,2)  NOT NULL,
  PRIMARY KEY (`codFactura`, `codDetalleFactura`),
  INDEX `fk_tbDetalleFactura_tbProducto:codProducto_idx` (`codProducto` ASC) VISIBLE,
  CONSTRAINT `fk_tbDetalleFactura_tbFactura:codFactura`
    FOREIGN KEY (`codFactura`)
    REFERENCES `ciberimpacto`.`tb_Factura` (`codFactura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbDetalleFactura_tbProducto:codProducto`
    FOREIGN KEY (`codProducto`)
    REFERENCES `ciberimpacto`.`tb_producto` (`codProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
